# pylint: skip-file
# Generated by Django 3.2.17 on 2023-02-06 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_identifier', models.CharField(default='changeme', max_length=4096)),
                ('raw_identifier', models.CharField(default='changeme', max_length=4096)),
                ('enrolled', models.DateTimeField()),
                ('last_fetched', models.DateTimeField()),
                ('last_uninstalled', models.DateTimeField(blank=True, null=True)),
                ('contact_after', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.TextField(default='{}', max_length=16777216)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('rule_json', models.TextField(default='[]', max_length=16777216)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.DateTimeField()),
                ('task', models.CharField(max_length=1024)),
                ('slug', models.SlugField(max_length=1024)),
                ('url', models.URLField(max_length=1024)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.TextField(default='{}', max_length=16777216)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='enrollment.enrollment')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='enrollment.enrollmentgroup'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='rule_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='enrollment.extensionruleset'),
        ),
    ]
